### PR TITLE
About section image  style changed.

### PR DESCRIPTION
**Pull request by E-fais**
Also made responsive with media query.

### CODE REVIEW

**Comment by E-fais** [comment]
fix #1

**Comment by E-fais** [comment]
@aparna2071  please review changes

**Review by aparna2071 — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution & your patience ❤️ 
Kindly just make changes for styling/CSS & please don't modify all the files.
Also, please add an extra line at the end of all CSS files that you are changing, so that there is no prettier issue.
If you face any issue, please contact me & sorry for late reply.

**Comment by E-fais** [comment]
Since you have set image as background instead of img tag, i had to change that code, I am not sure about styling a background image :)

**Review by aparna2071 — APPROVED** [review]
Thanks for your contribution & your interest in my portfolio website ❤️

**Comment by aparna2071** [comment]
You have done an outstanding work, appreciate your efforts ❤️
Thank you so much 🙂

**Comment by E-fais** [comment]
Thank you so much for accepting PR , always looking forward to contribute on HTML , CSS ,JS and React Js projects.

**Pull request merged**
